CREATE OR REPLACE FORCE VIEW trc_activity_log_v__ AS
SELECT
    a.id,
    a.workspace,
    a.workspace_display_name,
    a.apex_user,
    a.application_id,
    a.application_name,
    a.application_schema_owner,
    a.page_id,
    a.page_name,
    a.view_date,
    a.think_time,
    a.seconds_ago,
    a.log_context,
    a.elapsed_time,
    a.rows_queried,
    a.ip_address,
    a.agent,
    a.apex_session_id,
    a.application_tenant_id,
    a.error_message,
    a.error_on_component_type,
    a.error_on_component_name,
    a.page_view_mode,
    a.application_info,
    a.execution_chain_id,
    a.execution_id,
    a.interactive_report_id,
    a.ir_saved_report_id,
    a.ir_search,
    a.ws_application_id,
    a.ws_page_id,
    a.ws_datagrid_id,
    a.content_length,
    a.regions_from_cache,
    a.workspace_id,
    a.page_view_type,
    a.request_value,
    a.debug_page_view_id,
    a.view_timestamp,
    a.ecid
FROM apex_workspace_activity_log a;
--
COMMENT ON TABLE trc_activity_log_v__ IS '';

